export enum Message {
  ROLES_OBTAINED_SUCCESSFULLY = "COD100",
  NOT_ROLES_FOUND = "COD120",

  ACTOR_CREATED_SUCCESSFULLY = "COD200",
  ACTORS_OBTAINED_SUCCESSFULLY = "COD201",
  ACTOR_OBTAINED_SUCCESSFULLY = "COD202",
  ACTOR_UPDATED_SUCCESSFULLY = "COD203",
  ACTOR_ALREADY_EXISTS_EXCEPTION = "COD220",
  NOT_ACTORS_FOUND = "COD221",
  NOT_ACTOR_FOUND = "COD222",

  DEPARTMENT_CREATED_SUCCESSFULLY = "COD300",
  DEPARTMENTS_OBTAINED_SUCCESSFULLY = "COD301",
  DEPARTMENT_UPDATED_SUCCESSFULLY = "COD302",

  MAINTENANCE_TYPE_CREATED_SUCCESSFULLY = "COD400",
  MAINTENANCE_TYPES_OBTAINED_SUCCESSFULLY = "COD401",
  MAINTENANCE_TYPE_UPDATED_SUCCESSFULLY = "COD402",
  NOT_MAINTENANCE_TYPES_FOUND = "COD420",

  DEPT_MAINT_TYPE_ASSIGNMENT_CREATED_SUCCESSFULLY = "COD500",
  DEPT_MAINT_TYPE_ASSIGNMENTS_OBTAINED_SUCCESSFULLY = "COD501",
  DEPT_MAINT_TYPE_ASSIGNMENT_OBTAINED_SUCCESSFULLY = "COD502",
  DEPT_MAINT_TYPE_ASSIGNMENT_UPDATED_SUCCESSFULLY = "COD503",

  MAINTENANCE_CREATED_SUCCESSFULLY = "COD600",
  MAINTENANCES_OBTAINED_SUCCESSFULLY = "COD601",
  MAINTENANCE_OBTAINED_SUCCESSFULLY = "COD602",
  MAINTENANCE_UPDATED_SUCCESSFULLY = "COD603",

  STAGE_CREATED_SUCCESSFULLY = "COD700",
  STAGES_OBTAINED_SUCCESSFULLY = "COD701",
  STAGE_OBTAINED_SUCCESSFULLY = "COD702",
  STAGE_UPDATED_SUCCESSFULLY = "COD703",
  NOT_STAGES_FOUND = "COD720",
  NOT_STAGE_FOUND = "COD721",

  FILE_UPLOADED_SUCCESSFULLY = "COD_800",
  FORM_SAVED_SUCCESSFULLY = "COD_801",

  COORDINATOR_ALREADY_EXISTS = "COD900",
  NOT_COORDINATOR_FOUND = "COD901",

  BAD_REQUEST = "COD1000",
  INTERNAL_SERVER_ERROR = "COD5000",
}
